import json
import logging
import re
import uuid
from datetime import UTC, datetime
from decimal import Decimal
from difflib import SequenceMatcher
from typing import Any

from fastapi import HTTPException, status
from sqlalchemy import select
from sqlalchemy.orm import Session, selectinload

from app.models.document import DocumentChunk, UploadedDocument
from app.models.quiz import Quiz, QuizAnswer, QuizAttempt, QuizQuestion
from app.models.user import User
from app.schemas.quiz_schema import (
    QuestionType,
    QuizAnswerResult,
    QuizAttemptRead,
    QuizGenerateRequest,
    QuizQuestionRead,
    QuizRead,
    QuizSubmitRequest,
)
from app.services.llm_service import llm_service

logger = logging.getLogger(__name__)


class QuizService:
    def generate_quiz(self, db: Session, current_user: User, payload: QuizGenerateRequest) -> QuizRead:
        source_document = self._get_source_document(db, current_user, payload)
        document_context = self._build_document_context(db, source_document, payload) if source_document else None
        effective_question_count = self._effective_question_count(payload, document_context)
        effective_difficulty_distribution = self._difficulty_distribution(payload.difficulty.value, effective_question_count)
        self._log_document_generation_context(
            source_document,
            document_context,
            payload,
            effective_question_count,
            effective_difficulty_distribution,
        )

        system_prompt, user_prompt = self._build_generation_prompt(
            payload,
            source_document,
            document_context,
            effective_question_count,
            effective_difficulty_distribution,
        )
        llm_result = llm_service.generate_text_response(system_prompt=system_prompt, user_prompt=user_prompt)
        active_llm_result = llm_result
        generation_message = "Quiz generated by LLM."
        validation_errors: list[str] = []
        quiz_data: dict[str, Any] | None = None

        if llm_result.metadata.get("fallback"):
            validation_errors.append(llm_result.content)
        else:
            try:
                quiz_data = self._parse_llm_quiz(
                    llm_result.content,
                    payload,
                    source_document,
                    effective_question_count,
                    document_context,
                    effective_difficulty_distribution,
                )
            except ValueError as exc:
                validation_errors.append(str(exc))
                logger.warning(
                    "Quiz LLM output failed validation source_type=%s document_id=%s errors=%s",
                    payload.source_type.value,
                    str(source_document.id) if source_document else None,
                    validation_errors,
                )

        if quiz_data is None and not llm_result.metadata.get("fallback"):
            repaired_quiz, repair_result, repair_errors = self._try_repair_quiz_generation(
                payload=payload,
                document=source_document,
                document_context=document_context,
                invalid_content=llm_result.content,
                validation_errors=validation_errors,
                question_count=effective_question_count,
                difficulty_distribution=effective_difficulty_distribution,
            )
            validation_errors.extend(repair_errors)
            if repaired_quiz is not None and repair_result is not None:
                quiz_data = repaired_quiz
                active_llm_result = repair_result
                generation_message = "Quiz generated by LLM repair."

        if quiz_data is None:
            quiz_data = self._fallback_quiz(payload, source_document, document_context, effective_question_count)
            reason = "; ".join(validation_errors) if validation_errors else "LLM output unavailable or invalid."
            generation_message = f"Development fallback used: {reason}"

        logger.info(
            "Quiz generation completed source_type=%s document_id=%s question_type=%s requested_difficulty=%s effective_difficulty_distribution=%s generated_question_count=%s validation_errors=%s",
            payload.source_type.value,
            str(source_document.id) if source_document else None,
            payload.question_type.value,
            payload.difficulty.value,
            effective_difficulty_distribution,
            len(quiz_data.get("questions", [])),
            validation_errors,
        )
        db_difficulty = self._db_difficulty(payload.difficulty.value)
        quiz_topic = self._resolved_topic(payload, source_document, quiz_data)
        context_chunk_ids = document_context.get("chunk_ids", []) if document_context else []
        source_id = source_document.id if source_document else payload.source_id
        quiz = Quiz(
            user_id=current_user.id,
            source_type=payload.source_type.value,
            source_document_id=source_document.id if source_document else None,
            title=quiz_data["title"],
            topic=quiz_topic,
            description=quiz_data.get("description"),
            difficulty=db_difficulty,
            status="published",
            total_questions=len(quiz_data["questions"]),
            generated_by_ai=True,
            model_name=active_llm_result.model,
            metadata_={
                "question_type": payload.question_type.value,
                "requested_difficulty": payload.difficulty.value,
                "language": payload.language,
                "source_id": str(source_id) if source_id else None,
                "document_id": str(source_document.id) if source_document else None,
                "document_title": source_document.title if source_document else None,
                "focus_topic": payload.focus_topic,
                "context_chunk_ids": [str(chunk_id) for chunk_id in context_chunk_ids],
                "llm_provider": active_llm_result.provider,
                "llm_model": active_llm_result.model,
                "generation_message": generation_message,
                "context_length": document_context.get("context_length") if document_context else None,
                "requested_total_questions": payload.total_questions,
                "effective_total_questions": effective_question_count,
                "effective_difficulty_distribution": effective_difficulty_distribution,
            },
        )
        db.add(quiz)
        db.flush()

        for index, question_data in enumerate(quiz_data["questions"], start=1):
            question_type = self._normalize_question_type(question_data.get("question_type") or payload.question_type.value)
            difficulty = self._db_difficulty(question_data.get("difficulty") or payload.difficulty.value)
            db.add(
                QuizQuestion(
                    quiz_id=quiz.id,
                    question_order=index,
                    question_type=question_type,
                    question_text=question_data["question_text"],
                    options=self._normalize_options(question_data.get("options"), question_type),
                    correct_answer={"value": self._normalize_answer_value(question_data.get("correct_answer"))},
                    explanation=question_data.get("explanation"),
                    topic=question_data.get("topic") or quiz_topic,
                    difficulty=difficulty,
                    source_chunk_ids=context_chunk_ids,
                    metadata_={"requested_difficulty": payload.difficulty.value, "focus_topic": payload.focus_topic, "language": payload.language},
                )
            )

        db.commit()
        db.refresh(quiz)
        return self.get_quiz(db=db, current_user=current_user, quiz_id=quiz.id)

    def get_quizzes(self, db: Session, current_user: User) -> list[QuizRead]:
        quizzes = db.scalars(
            select(Quiz)
            .options(selectinload(Quiz.questions))
            .where(Quiz.user_id == current_user.id)
            .order_by(Quiz.created_at.desc())
        ).all()
        return [self._to_quiz_read(quiz) for quiz in quizzes]

    def get_quiz(self, db: Session, current_user: User, quiz_id: uuid.UUID) -> QuizRead:
        quiz = db.scalar(
            select(Quiz)
            .options(selectinload(Quiz.questions))
            .where(Quiz.id == quiz_id, Quiz.user_id == current_user.id)
        )
        if not quiz:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Quiz not found.")
        return self._to_quiz_read(quiz)

    def submit_quiz(
        self,
        db: Session,
        current_user: User,
        quiz_id: uuid.UUID,
        payload: QuizSubmitRequest,
    ) -> QuizAttemptRead:
        quiz = db.scalar(
            select(Quiz)
            .options(selectinload(Quiz.questions))
            .where(Quiz.id == quiz_id, Quiz.user_id == current_user.id)
        )
        if not quiz:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Quiz not found.")

        questions_by_id = {question.id: question for question in quiz.questions}
        submitted_answers = {answer.question_id: str(answer.user_answer).strip() for answer in payload.answers}
        now = datetime.now(UTC)
        total_questions = len(quiz.questions)
        correct_count = 0
        answer_results: list[QuizAnswerResult] = []
        wrong_topics: list[str] = []

        attempt = QuizAttempt(
            quiz_id=quiz.id,
            user_id=current_user.id,
            status="submitted",
            submitted_at=now,
            graded_at=now,
            max_score=Decimal("100"),
            weak_topics=[],
            metadata_={},
        )
        db.add(attempt)
        db.flush()

        quiz_language = str((quiz.metadata_ or {}).get("language") or "id")

        for question in sorted(quiz.questions, key=lambda item: item.question_order):
            user_answer = submitted_answers.get(question.id, "")
            correct_answer = self._correct_answer_value(question)
            question_type = self._normalize_question_type(question.question_type)

            if question_type == "short_answer":
                evaluation = self.evaluate_short_answer(
                    user_answer=user_answer,
                    correct_answer=correct_answer,
                    explanation=question.explanation,
                    question_text=question.question_text,
                    context=question.topic,
                    question_id=question.id,
                    language=quiz_language,
                )
            else:
                is_exact_correct = self._is_correct_by_question_type(user_answer, correct_answer, question_type)
                evaluation = {
                    "is_correct": is_exact_correct,
                    "similarity_score": None,
                    "feedback": question.explanation or self._exact_answer_feedback(is_exact_correct, quiz_language),
                    "llm_evaluator_used": False,
                }

            is_correct = bool(evaluation["is_correct"])
            feedback = str(evaluation.get("feedback") or question.explanation or "")
            similarity_score = evaluation.get("similarity_score") if question_type == "short_answer" else None

            if is_correct:
                correct_count += 1
            elif question.topic:
                wrong_topics.append(question.topic)

            db.add(
                QuizAnswer(
                    attempt_id=attempt.id,
                    question_id=question.id,
                    user_id=current_user.id,
                    answer={
                        "value": user_answer,
                        "similarity_score": similarity_score,
                        "rule_similarity": evaluation.get("rule_similarity"),
                        "keyword_overlap": evaluation.get("keyword_overlap"),
                        "llm_evaluator_used": evaluation.get("llm_evaluator_used", False),
                    },
                    is_correct=is_correct,
                    score_awarded=Decimal("1") if is_correct else Decimal("0"),
                    feedback=feedback,
                )
            )
            answer_results.append(
                QuizAnswerResult(
                    question_id=question.id,
                    question_text=question.question_text,
                    user_answer=user_answer,
                    correct_answer=correct_answer,
                    is_correct=is_correct,
                    similarity_score=similarity_score,
                    feedback=feedback,
                    explanation=question.explanation,
                    topic=question.topic,
                )
            )
        wrong_count = total_questions - correct_count
        score = round((correct_count / total_questions) * 100, 2) if total_questions else 0.0
        weak_topics = sorted(set(wrong_topics))
        recommended_review = self._recommended_review(weak_topics, quiz_language)

        attempt.score = Decimal(str(score))
        attempt.percentage = Decimal(str(score))
        attempt.weak_topics = weak_topics
        attempt.ai_feedback = "; ".join(recommended_review) if recommended_review else ("Kerja bagus. Pertahankan latihanmu." if quiz_language == "id" else "Great work. Keep practicing.")
        attempt.metadata_ = {
            "total_questions": total_questions,
            "correct_count": correct_count,
            "wrong_count": wrong_count,
            "recommended_review": recommended_review,
            "language": quiz_language,
        }

        db.commit()
        db.refresh(attempt)
        return self._to_attempt_read(attempt, quiz=quiz, answer_results=answer_results)

    def get_recent_attempts(self, db: Session, current_user: User, limit: int = 10) -> list[QuizAttemptRead]:
        attempts = db.scalars(
            select(QuizAttempt)
            .options(selectinload(QuizAttempt.quiz), selectinload(QuizAttempt.answers).selectinload(QuizAnswer.question))
            .where(QuizAttempt.user_id == current_user.id)
            .order_by(QuizAttempt.created_at.desc())
            .limit(limit)
        ).all()
        return [self._to_attempt_read(attempt) for attempt in attempts]

    def get_quiz_attempts(self, db: Session, current_user: User, quiz_id: uuid.UUID) -> list[QuizAttemptRead]:
        quiz = db.scalar(select(Quiz).where(Quiz.id == quiz_id, Quiz.user_id == current_user.id))
        if not quiz:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Quiz not found.")

        attempts = db.scalars(
            select(QuizAttempt)
            .options(selectinload(QuizAttempt.quiz), selectinload(QuizAttempt.answers).selectinload(QuizAnswer.question))
            .where(QuizAttempt.quiz_id == quiz_id, QuizAttempt.user_id == current_user.id)
            .order_by(QuizAttempt.created_at.desc())
        ).all()
        return [self._to_attempt_read(attempt) for attempt in attempts]

    def _get_source_document(self, db: Session, current_user: User, payload: QuizGenerateRequest) -> UploadedDocument | None:
        if payload.source_type.value != "document":
            return None

        document_id = payload.document_id or payload.source_id
        if not document_id:
            raise HTTPException(
                status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
                detail="document_id or source_id is required for document quizzes.",
            )

        document = db.scalar(
            select(UploadedDocument).where(
                UploadedDocument.id == document_id,
                UploadedDocument.user_id == current_user.id,
            )
        )
        if not document:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Source document not found.")
        return document

    def _build_document_context(
        self,
        db: Session,
        document: UploadedDocument,
        payload: QuizGenerateRequest,
    ) -> dict[str, Any]:
        if document.status != "ready":
            raise HTTPException(
                status_code=status.HTTP_409_CONFLICT,
                detail=f"Source document is not ready for quiz generation. Current status: {document.status}.",
            )

        chunks = db.scalars(
            select(DocumentChunk)
            .where(DocumentChunk.document_id == document.id, DocumentChunk.user_id == document.user_id)
            .order_by(DocumentChunk.chunk_index)
        ).all()

        if not chunks:
            raise HTTPException(
                status_code=status.HTTP_409_CONFLICT,
                detail="Source document has no extractable chunks for quiz generation.",
            )

        quizworthy_chunks = [chunk for chunk in chunks if self._is_quizworthy_chunk(chunk.content)]
        if not quizworthy_chunks:
            quizworthy_chunks = chunks

        selected_chunks = self._select_document_chunks(quizworthy_chunks, payload.focus_topic)
        context = self._format_document_context(selected_chunks)
        context_length = len(context)

        if context_length < 500:
            raise HTTPException(
                status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
                detail="Document context is too short to generate a reliable quiz.",
            )

        return {
            "document_id": document.id,
            "document_title": document.title,
            "document_summary": document.summary or "",
            "focus_topic": payload.focus_topic,
            "total_document_chunks": len(chunks),
            "selected_chunks_count": len(selected_chunks),
            "chunk_ids": [chunk.id for chunk in selected_chunks],
            "context": context,
            "context_length": context_length,
            "language": payload.language,
            "detected_language": self._detect_quiz_language(" ".join([document.title or "", payload.focus_topic or "", context[:2500]])),
        }

    def _select_document_chunks(self, chunks: list[DocumentChunk], focus_topic: str | None) -> list[DocumentChunk]:
        if not chunks:
            return []

        max_chunks = 10
        sorted_chunks = sorted(chunks, key=lambda chunk: chunk.chunk_index)
        if len(sorted_chunks) <= max_chunks:
            return sorted_chunks

        selected_indexes: set[int] = set()
        chunks_by_index = {chunk.chunk_index: chunk for chunk in sorted_chunks}

        if focus_topic:
            terms = self._important_terms(focus_topic)
            scored_chunks = [(self._document_chunk_score(terms, chunk.content), chunk) for chunk in sorted_chunks]
            scored_chunks.sort(key=lambda item: (item[0], -item[1].chunk_index), reverse=True)

            for score, chunk in scored_chunks[:6]:
                if score <= 0:
                    continue
                selected_indexes.add(chunk.chunk_index)
                if chunk.chunk_index - 1 in chunks_by_index:
                    selected_indexes.add(chunk.chunk_index - 1)
                if chunk.chunk_index + 1 in chunks_by_index:
                    selected_indexes.add(chunk.chunk_index + 1)

        for chunk in self._representative_chunks(sorted_chunks, max_chunks=6):
            selected_indexes.add(chunk.chunk_index)

        selected = [chunks_by_index[index] for index in sorted(selected_indexes) if index in chunks_by_index]
        if not selected:
            selected = self._representative_chunks(sorted_chunks, max_chunks=max_chunks)

        return selected[:max_chunks]

    def _representative_chunks(self, chunks: list[DocumentChunk], max_chunks: int) -> list[DocumentChunk]:
        if len(chunks) <= max_chunks:
            return chunks

        indexes = {0, len(chunks) - 1}
        if len(chunks) > 2:
            indexes.add(len(chunks) // 2)
        slots = max(max_chunks - len(indexes), 0)
        if slots:
            step = (len(chunks) - 1) / (slots + 1)
            for slot in range(1, slots + 1):
                indexes.add(round(step * slot))

        selected = [chunks[index] for index in sorted(indexes) if 0 <= index < len(chunks)]
        return selected[:max_chunks]

    def _format_document_context(self, chunks: list[DocumentChunk]) -> str:
        blocks: list[str] = []
        total_length = 0
        max_context_chars = 11000
        per_chunk_limit = 1400

        for chunk in chunks:
            cleaned = self._clean_document_text(chunk.content)
            excerpt = self._trim_to_sentence(cleaned, per_chunk_limit)
            if not excerpt:
                continue
            block = (
                f"Document chunk {chunk.chunk_index + 1} "
                f"chunk_id={chunk.id} page={self._format_chunk_page(chunk)}:\n{excerpt}"
            )
            if total_length + len(block) > max_context_chars:
                break
            blocks.append(block)
            total_length += len(block)

        return "\n\n".join(blocks)

    def _effective_question_count(self, payload: QuizGenerateRequest, document_context: dict[str, Any] | None) -> int:
        requested = max(1, min(int(payload.total_questions or 5), 20))
        if not document_context:
            return requested

        context_length = int(document_context.get("context_length") or 0)
        max_from_context = max(1, min(10, context_length // 900))
        return min(requested, max_from_context)

    def _difficulty_distribution(self, difficulty: str, question_count: int) -> list[str]:
        normalized = str(difficulty or "medium").strip().lower()
        count = max(1, int(question_count or 1))
        if normalized != "adaptive":
            return [normalized if normalized in {"easy", "medium", "hard"} else "medium"] * count

        if count == 1:
            return ["medium"]
        if count == 2:
            return ["easy", "medium"]

        easy_count = max(1, round(count * 0.4))
        hard_count = max(1, round(count * 0.2))
        medium_count = max(1, count - easy_count - hard_count)
        while easy_count + medium_count + hard_count > count:
            if medium_count > 1:
                medium_count -= 1
            elif easy_count > 1:
                easy_count -= 1
            else:
                hard_count -= 1
        while easy_count + medium_count + hard_count < count:
            medium_count += 1
        return (["easy"] * easy_count) + (["medium"] * medium_count) + (["hard"] * hard_count)

    def _log_document_generation_context(
        self,
        document: UploadedDocument | None,
        document_context: dict[str, Any] | None,
        payload: QuizGenerateRequest,
        effective_question_count: int,
        difficulty_distribution: list[str] | None = None,
    ) -> None:
        if not document or not document_context:
            return

        logger.info(
            "Quiz document context source_type=%s document_id=%s focus_topic=%r total_document_chunks=%s selected_chunks_count=%s selected_chunk_ids=%s context_length=%s requested_difficulty=%s effective_difficulty_distribution=%s question_type=%s requested_questions=%s effective_questions=%s",
            payload.source_type.value,
            document.id,
            payload.focus_topic,
            document_context.get("total_document_chunks"),
            document_context.get("selected_chunks_count"),
            [str(chunk_id) for chunk_id in document_context.get("chunk_ids", [])],
            document_context.get("context_length"),
            payload.difficulty.value,
            difficulty_distribution or [],
            payload.question_type.value,
            payload.total_questions,
            effective_question_count,
        )

    def _build_generation_prompt(
        self,
        payload: QuizGenerateRequest,
        document: UploadedDocument | None,
        document_context: dict[str, Any] | None,
        question_count: int,
        difficulty_distribution: list[str],
    ) -> tuple[str, str]:
        is_document_mode = document is not None and document_context is not None
        quiz_topic = self._resolved_topic(payload, document, {})
        language = payload.language
        response_language = "Indonesian" if language == "id" else "English"
        true_false_options = ["Benar", "Salah"] if language == "id" else ["True", "False"]

        system_prompt = (
            "You are EduPath AI Quiz Generator. Create high-quality learning assessments. "
            "Return only valid JSON. Do not wrap the JSON in markdown. Do not include commentary outside the JSON."
        )

        if is_document_mode:
            instruction = "Generate quiz questions only from the provided document context."
            source_context = {
                "type": "document",
                "document_id": str(document.id),
                "document_title": document.title,
                "document_summary": document.summary or "",
                "focus_topic": payload.focus_topic,
                "topic_for_quiz": quiz_topic,
                "language": language,
                "document_context": document_context["context"],
            }
            rules = [
                "Generate quiz questions only from the provided document context.",
                "Do not create generic questions.",
                "Do not ask 'Which statement is supported by the uploaded document'.",
                "Do not mention 'uploaded document' in question_text or answer options.",
                "Create direct learning questions about concepts, definitions, processes, methods, findings, examples, or comparisons found in the document.",
                "Each question must be unique and specific to the document content.",
                "Each option must be concise and meaningful.",
                "Wrong options must be plausible but clearly incorrect based on the context.",
                "Correct answer must exactly match one of the provided options for multiple_choice.",
                "Explanation must cite the relevant idea from the document in 1-2 concise sentences, without inline citation labels.",
                "If focus_topic is provided, prioritize document chunks related to that focus topic.",
                f"Write the quiz in {response_language}; keep technical terms as needed.",
            ]
        else:
            instruction = "Generate a learning quiz from the provided topic using reliable general knowledge."
            source_context = {
                "type": payload.source_type.value,
                "topic": quiz_topic,
                "language": language,
            }
            rules = [
                "Create direct learning questions about the topic.",
                "Do not use filler or meta questions.",
                "Each question must be unique.",
                "Each explanation should teach why the answer is correct.",
                f"Write the quiz in {response_language}; keep technical terms as needed.",
            ]

        user_prompt = json.dumps(
            {
                "instruction": instruction,
                "response_language": response_language,
                "required_schema": {
                    "title": "string",
                    "topic": "string",
                    "difficulty": payload.difficulty.value,
                    "question_type": payload.question_type.value,
                    "questions": [
                        {
                            "question_text": "string",
                            "question_type": payload.question_type.value,
                            "options": ["string", "string", "string", "string"] if payload.question_type.value == "multiple_choice" else (true_false_options if payload.question_type.value == "true_false" else []),
                            "correct_answer": "string",
                            "explanation": "string",
                            "topic": "specific subtopic string",
                            "difficulty": "easy | medium | hard",
                        }
                    ],
                },
                "rules": [
                    f"Generate exactly {question_count} questions.",
                    f"Use exactly this question_type for every question: {payload.question_type.value}.",
                    "For multiple_choice, every question must have exactly 4 options and the correct_answer must exactly equal one option text.",
                    f"For true_false, every question must be a clear true/false statement and options must be exactly {true_false_options}.",
                    "For short_answer, options must be an empty list and correct_answer must be a concise expected answer.",
                    f"All title, topic, question_text, options, correct_answer, and explanation fields must be in {response_language}, except established technical terms.",
                    "Follow the difficulty_plan in order. For adaptive, mix easy, medium, and hard as specified.",
                    "Easy questions test definitions, direct facts, or basic terms.",
                    "Medium questions test understanding, relationships, examples, or application.",
                    "Hard questions test analysis, comparison, or inference across multiple ideas.",
                    *rules,
                ],
                "bad_patterns_to_avoid": [
                    "Which statement is supported by the uploaded document",
                    "The uploaded document says this topic is unrelated",
                    "The uploaded document contains only metadata",
                    "The document provides no learning material",
                ],
                "difficulty_plan": difficulty_distribution,
                "input": {
                    "source": source_context,
                    "difficulty": payload.difficulty.value,
                    "question_type": payload.question_type.value,
                    "language": language,
                    "total_questions": question_count,
                },
            },
            ensure_ascii=False,
        )
        return system_prompt, user_prompt

    def _try_repair_quiz_generation(
        self,
        *,
        payload: QuizGenerateRequest,
        document: UploadedDocument | None,
        document_context: dict[str, Any] | None,
        invalid_content: str,
        validation_errors: list[str],
        question_count: int,
        difficulty_distribution: list[str],
    ) -> tuple[dict[str, Any] | None, Any | None, list[str]]:
        system_prompt, user_prompt = self._build_repair_prompt(
            payload=payload,
            document=document,
            document_context=document_context,
            invalid_content=invalid_content,
            validation_errors=validation_errors,
            question_count=question_count,
            difficulty_distribution=difficulty_distribution,
        )
        repair_result = llm_service.generate_text_response(system_prompt=system_prompt, user_prompt=user_prompt)
        if repair_result.metadata.get("fallback"):
            return None, repair_result, [f"Repair LLM unavailable: {repair_result.content}"]

        try:
            repaired = self._parse_llm_quiz(
                repair_result.content,
                payload,
                document,
                question_count,
                document_context,
                difficulty_distribution,
            )
            return repaired, repair_result, []
        except ValueError as exc:
            logger.warning(
                "Quiz repair output failed validation source_type=%s document_id=%s error=%s",
                payload.source_type.value,
                str(document.id) if document else None,
                exc,
            )
            return None, repair_result, [f"Repair failed validation: {exc}"]

    def _build_repair_prompt(
        self,
        *,
        payload: QuizGenerateRequest,
        document: UploadedDocument | None,
        document_context: dict[str, Any] | None,
        invalid_content: str,
        validation_errors: list[str],
        question_count: int,
        difficulty_distribution: list[str],
    ) -> tuple[str, str]:
        base_system, base_user = self._build_generation_prompt(
            payload,
            document,
            document_context,
            question_count,
            difficulty_distribution,
        )
        repair_payload = {
            "repair_instruction": "Fix this quiz JSON. Remove generic questions, create specific document-based questions, and return valid JSON only.",
            "validation_errors": validation_errors,
            "original_generation_request": json.loads(base_user),
            "invalid_quiz_json_or_text": self._compact_text(invalid_content, 5000),
        }
        return base_system, json.dumps(repair_payload, ensure_ascii=False)

    def _parse_llm_quiz(
        self,
        content: str,
        payload: QuizGenerateRequest,
        document: UploadedDocument | None = None,
        question_count: int | None = None,
        document_context: dict[str, Any] | None = None,
        difficulty_distribution: list[str] | None = None,
    ) -> dict[str, Any]:
        json_text = self._extract_json(content)
        try:
            parsed = json.loads(json_text)
        except json.JSONDecodeError as exc:
            raise ValueError("LLM did not return valid JSON.") from exc

        questions = parsed.get("questions")
        if not isinstance(parsed.get("title"), str) or not parsed.get("title").strip():
            raise ValueError("LLM JSON is missing title.")
        if not isinstance(questions, list) or not questions:
            raise ValueError("LLM JSON is missing questions.")

        expected_count = max(1, min(question_count or payload.total_questions, payload.total_questions))
        planned_difficulties = difficulty_distribution or self._difficulty_distribution(payload.difficulty.value, expected_count)
        default_topic = self._resolved_topic(payload, document, parsed)
        requested_type = self._normalize_question_type(payload.question_type.value)
        validation_errors: list[str] = []
        seen_questions: set[str] = set()
        normalized_questions: list[dict[str, Any]] = []

        for raw_question in questions:
            if len(normalized_questions) >= expected_count:
                break
            if not isinstance(raw_question, dict):
                validation_errors.append("Question item is not an object.")
                continue

            question_text = self._compact_text(raw_question.get("question_text") or "", 320)
            question_key = self._normalized_for_scoring(question_text)
            if not question_text:
                validation_errors.append("Question text is empty.")
                continue
            if question_key in seen_questions:
                validation_errors.append(f"Duplicate question rejected: {question_text}")
                continue
            if self._is_generic_question(question_text):
                validation_errors.append(f"Generic question rejected: {question_text}")
                continue

            raw_type = self._normalize_question_type(raw_question.get("question_type") or requested_type)
            if raw_type != requested_type:
                validation_errors.append(f"Question type {raw_type} does not match requested type {requested_type}.")
                continue

            planned_difficulty = planned_difficulties[min(len(normalized_questions), len(planned_difficulties) - 1)]
            difficulty = str(raw_question.get("difficulty") or planned_difficulty).strip().lower()
            if difficulty not in {"easy", "medium", "hard"}:
                difficulty = planned_difficulty

            options: list[str]
            correct_answer: str
            if requested_type == "multiple_choice":
                options = self._normalize_options(raw_question.get("options"), requested_type)
                options = [self._compact_text(option, 180) for option in options]
                if len(options) != 4:
                    validation_errors.append(f"Multiple choice question does not have exactly 4 options: {question_text}")
                    continue
                if self._are_options_low_quality(options):
                    validation_errors.append(f"Low-quality options rejected for question: {question_text}")
                    continue
                correct_answer = self._resolve_correct_answer(raw_question.get("correct_answer"), options)
                if not correct_answer:
                    validation_errors.append(f"Correct answer does not match an option for question: {question_text}")
                    continue
            elif requested_type == "true_false":
                options = self._true_false_options(raw_question.get("options"), {"language": payload.language})
                correct_answer = self._resolve_true_false_answer(raw_question.get("correct_answer"), options)
                if not correct_answer:
                    validation_errors.append(f"True/false correct answer is invalid for question: {question_text}")
                    continue
            else:
                options = []
                correct_answer = self._compact_text(raw_question.get("correct_answer") or "", 180)
                if not correct_answer:
                    validation_errors.append(f"Short answer correct answer is empty for question: {question_text}")
                    continue

            explanation = self._compact_text(raw_question.get("explanation") or "", 420)
            if not explanation:
                validation_errors.append(f"Explanation is empty for question: {question_text}")
                continue
            if self._is_generic_question(explanation):
                validation_errors.append(f"Generic explanation rejected for question: {question_text}")
                continue

            topic = self._compact_text(raw_question.get("topic") or default_topic, 120)
            if not topic:
                validation_errors.append(f"Topic is empty for question: {question_text}")
                continue

            seen_questions.add(question_key)
            normalized_questions.append(
                {
                    "question_text": question_text,
                    "question_type": requested_type,
                    "options": options,
                    "correct_answer": correct_answer,
                    "explanation": explanation,
                    "topic": topic,
                    "difficulty": difficulty,
                }
            )

        if len(normalized_questions) < expected_count:
            validation_errors.append(f"Only {len(normalized_questions)} valid questions generated; expected {expected_count}.")
            logger.warning(
                "Quiz validation errors source_type=%s document_id=%s errors=%s",
                payload.source_type.value,
                str(document.id) if document else None,
                validation_errors[:8],
            )
            raise ValueError("; ".join(validation_errors[:8]))

        if validation_errors:
            logger.info(
                "Quiz validation skipped invalid extras source_type=%s document_id=%s skipped_errors=%s",
                payload.source_type.value,
                str(document.id) if document else None,
                validation_errors[:8],
            )

        return {
            "title": self._compact_text(parsed["title"], 160),
            "description": self._compact_text(parsed.get("description") or "", 280),
            "topic": self._compact_text(parsed.get("topic") or default_topic, 160),
            "questions": normalized_questions,
        }

    def _extract_json(self, content: str) -> str:
        cleaned = content.strip()
        fence_match = re.search(r"```(?:json)?\s*(.*?)```", cleaned, re.DOTALL | re.IGNORECASE)
        if fence_match:
            cleaned = fence_match.group(1).strip()
        start = cleaned.find("{")
        end = cleaned.rfind("}")
        if start == -1 or end == -1 or end <= start:
            raise ValueError("LLM response does not contain a JSON object.")
        return cleaned[start : end + 1]

    def _fallback_quiz(
        self,
        payload: QuizGenerateRequest,
        document: UploadedDocument | None = None,
        document_context: dict[str, Any] | None = None,
        question_count: int | None = None,
    ) -> dict[str, Any]:
        if document and document_context:
            return self._fallback_document_quiz(payload, document, document_context, question_count)
        return self._fallback_topic_quiz(payload, question_count)

    def _fallback_document_quiz(
        self,
        payload: QuizGenerateRequest,
        document: UploadedDocument,
        document_context: dict[str, Any],
        question_count: int | None = None,
    ) -> dict[str, Any]:
        question_type = payload.question_type.value
        topic = self._resolved_topic(payload, document, {})
        language = payload.language
        sentences = self._fallback_source_sentences(document_context)
        if not sentences:
            raise HTTPException(
                status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
                detail="Document context is not sufficient to generate a fallback quiz.",
            )

        expected_count = max(1, min(question_count or payload.total_questions, payload.total_questions, len(sentences)))
        difficulties = self._difficulty_distribution(payload.difficulty.value, expected_count)
        concepts = self._extract_key_concepts(" ".join([topic, document.title or "", document_context.get("context", "")]))
        main_concept = payload.focus_topic or (concepts[0] if concepts else topic)
        questions: list[dict[str, Any]] = []

        id_templates = [
            "Apa ide utama tentang {concept} yang dijelaskan dalam dokumen?",
            "Bagaimana dokumen menjelaskan peran {concept}?",
            "Poin mana yang paling tepat menggambarkan {concept} dalam materi?",
            "Apa hubungan penting yang dibahas dokumen terkait {concept}?",
            "Kesimpulan apa yang dapat diambil tentang {concept} dari materi?",
        ]
        en_templates = [
            "What main idea about {concept} is explained in the material?",
            "How does the material describe the role of {concept}?",
            "Which point best describes {concept} in the material?",
            "What important relationship is discussed about {concept}?",
            "What conclusion can be drawn about {concept} from the material?",
        ]
        templates = id_templates if language == "id" else en_templates

        for index in range(expected_count):
            sentence = sentences[index % len(sentences)]
            concept = concepts[index % len(concepts)] if concepts else main_concept
            answer = self._extract_definition_answer(sentence) or self._compact_text(sentence, 150)
            difficulty = difficulties[min(index, len(difficulties) - 1)]

            if question_type == "true_false":
                options = ["Benar", "Salah"] if language == "id" else ["True", "False"]
                question_text = (f"Benar atau salah: {answer}" if language == "id" else f"True or false: {answer}")
                correct_answer = options[0]
            elif question_type == "short_answer":
                options = []
                question_text = templates[index % len(templates)].format(concept=concept)
                correct_answer = answer
            else:
                distractors = self._fallback_distractors(language, answer)
                options = [answer, *distractors[:3]]
                question_text = templates[index % len(templates)].format(concept=concept)
                correct_answer = answer

            questions.append(
                {
                    "question_text": question_text,
                    "question_type": question_type,
                    "options": options,
                    "correct_answer": correct_answer,
                    "explanation": (
                        f"Jawaban ini diringkas dari bagian materi yang membahas {concept}: {self._compact_text(sentence, 180)}"
                        if language == "id"
                        else f"This answer is summarized from the material section about {concept}: {self._compact_text(sentence, 180)}"
                    ),
                    "topic": concept,
                    "difficulty": difficulty,
                }
            )

        title = f"{document.title} Quiz" if not payload.focus_topic else f"{payload.focus_topic} Quiz from {document.title}"
        return {
            "title": title,
            "description": "Development fallback quiz generated from selected document context.",
            "topic": topic,
            "questions": questions,
        }

    def _fallback_topic_quiz(self, payload: QuizGenerateRequest, question_count: int | None = None) -> dict[str, Any]:
        topic = payload.topic or ("Tinjauan Umum" if payload.language == "id" else "General Review")
        language = payload.language
        question_type = payload.question_type.value
        expected_count = max(1, min(question_count or payload.total_questions, payload.total_questions))
        difficulties = self._difficulty_distribution(payload.difficulty.value, expected_count)
        questions: list[dict[str, Any]] = []

        for index in range(expected_count):
            difficulty = difficulties[min(index, len(difficulties) - 1)]
            if question_type == "true_false":
                options = ["Benar", "Salah"] if language == "id" else ["True", "False"]
                correct_answer = options[0]
                text = (
                    f"Benar atau salah: {topic} adalah konsep penting dalam topik quiz ini."
                    if language == "id"
                    else f"True or false: {topic} is an important concept in this quiz topic."
                )
            elif question_type == "short_answer":
                options = []
                correct_answer = topic
                text = (
                    f"Sebutkan satu ide penting yang berkaitan dengan {topic}."
                    if language == "id"
                    else f"What is one key idea related to {topic}?"
                )
            else:
                if language == "id":
                    options = [
                        f"Konsep utama yang berkaitan dengan {topic}",
                        "Pendekatan yang hanya memakai aturan tetap tanpa belajar dari data",
                        "Proses manual yang mengelompokkan informasi tanpa menemukan pola",
                        "Metode yang membuat keputusan acak tanpa mempertimbangkan data",
                    ]
                    text = f"Pilihan mana yang paling mewakili ide utama dalam {topic}?"
                else:
                    options = [
                        f"A key concept related to {topic}",
                        "An approach that only uses fixed rules without learning from data",
                        "A manual process that groups information without finding patterns",
                        "A method that makes random decisions without considering data",
                    ]
                    text = f"Which option best represents a key idea in {topic}?"
                correct_answer = options[0]

            questions.append(
                {
                    "question_text": text,
                    "question_type": question_type,
                    "options": options,
                    "correct_answer": correct_answer,
                    "explanation": (
                        f"Pertanyaan fallback ini tetap difokuskan pada {topic}."
                        if language == "id"
                        else f"This fallback question keeps the quiz focused on {topic}."
                    ),
                    "topic": topic,
                    "difficulty": difficulty,
                }
            )

        return {
            "title": f"Quiz {topic}" if language == "id" else f"{topic} Quiz",
            "description": (
                "Quiz fallback dibuat karena output LLM tidak tersedia atau tidak valid."
                if language == "id"
                else "Development fallback quiz generated because LLM output was unavailable or invalid."
            ),
            "topic": topic,
            "questions": questions,
        }
    def _resolved_topic(
        self,
        payload: QuizGenerateRequest,
        document: UploadedDocument | None,
        quiz_data: dict[str, Any],
    ) -> str:
        topic = quiz_data.get("topic") or payload.focus_topic or payload.topic
        if topic:
            return str(topic).strip()
        if document:
            return document.title
        return "General Review"

    def _fallback_source_sentences(self, document_context: dict[str, Any] | None) -> list[str]:
        if not document_context:
            return []

        context = str(document_context.get("context") or "")
        context = re.sub(r"Document chunk \d+\s+chunk_id=[^:]+:\s*", " ", context)
        context = self._clean_document_text(context)
        sentences = [sentence.strip() for sentence in re.split(r"(?<=[.!?])\s+", re.sub(r"\s+", " ", context))]
        return [sentence for sentence in sentences if 50 <= len(sentence) <= 260 and not self._is_metadata_like(sentence)][:12]

    def _extract_definition_answer(self, sentence: str) -> str | None:
        patterns = [r"\badalah\b", r"\bmerupakan\b", r"\bis\b", r"\bare\b", r"\brefers to\b"]
        for pattern in patterns:
            match = re.search(pattern, sentence, flags=re.IGNORECASE)
            if match:
                answer = sentence[match.end() :].strip(" :,-")
                return self._compact_text(answer, 150) if len(answer) >= 20 else self._compact_text(sentence, 150)
        return None

    def _fallback_distractors(self, language: str, correct_answer: str) -> list[str]:
        if language == "id":
            return [
                "Pendekatan yang hanya memakai aturan tetap tanpa belajar dari data",
                "Proses manual yang mengelompokkan informasi tanpa menemukan pola",
                "Metode yang membuat keputusan acak tanpa mempertimbangkan data",
            ]
        return [
            "An approach that only uses fixed rules without learning from data",
            "A manual process that groups information without finding patterns",
            "A method that makes random decisions without considering data",
        ]

    def _extract_key_concepts(self, text: str) -> list[str]:
        terms = self._important_terms(text)
        counts: dict[str, int] = {}
        for term in terms:
            counts[term] = counts.get(term, 0) + 1
        ranked = sorted(counts.items(), key=lambda item: (-item[1], item[0]))
        concepts = [term.replace("_", " ").title() for term, count in ranked if count >= 2]
        return concepts[:8] or [term.replace("_", " ").title() for term in terms[:5]]

    def _important_terms(self, text: str) -> list[str]:
        stopwords = {
            "a", "an", "and", "are", "as", "at", "be", "by", "for", "from", "in", "is", "it", "of", "on", "or", "that", "the", "this", "to", "with", "into", "only", "about", "between", "using", "used",
            "apa", "adalah", "atau", "dalam", "dan", "dari", "di", "ini", "itu", "ke", "pada", "sebagai", "untuk", "yang", "dengan", "oleh", "karena", "akan", "dapat", "secara", "tentang", "menjadi", "memiliki",
        }
        normalized = text.lower().replace("_", " ")
        return [token for token in re.findall(r"[a-zA-Z0-9]+", normalized) if len(token) > 2 and token not in stopwords]

    def _keyword_overlap_score(self, query_terms: list[str], chunk_text: str) -> float:
        if not query_terms:
            return 0.0

        chunk_terms = set(re.findall(r"[a-zA-Z0-9]+", chunk_text.lower().replace("_", " ")))
        if not chunk_terms:
            return 0.0

        matched = sum(1 for term in query_terms if term in chunk_terms)
        return matched / max(len(query_terms), 1)

    def _document_chunk_score(self, query_terms: list[str], chunk_text: str) -> float:
        if not query_terms:
            return 0.0

        normalized_chunk = re.sub(r"\s+", " ", chunk_text.lower().replace("_", " "))
        token_score = self._keyword_overlap_score(query_terms, chunk_text)
        phrase_score = 0.0
        for phrase_size in (4, 3, 2):
            for index in range(0, max(len(query_terms) - phrase_size + 1, 0)):
                phrase = " ".join(query_terms[index : index + phrase_size])
                if phrase and phrase in normalized_chunk:
                    phrase_score += 0.25

        return min(1.0, token_score + phrase_score)

    def _is_quizworthy_chunk(self, text: str) -> bool:
        cleaned = self._clean_document_text(text)
        if len(cleaned) < 120:
            return False
        words = re.findall(r"[a-zA-Z0-9]+", cleaned)
        if len(words) < 18:
            return False
        return not self._is_metadata_like(cleaned[:300])

    def _clean_document_text(self, text: str) -> str:
        lines = []
        for raw_line in str(text or "").splitlines():
            line = re.sub(r"\s+", " ", raw_line).strip()
            if not line:
                continue
            if self._is_metadata_like(line):
                continue
            line = re.sub(r"https?://\S+|www\.\S+", "", line).strip()
            if line:
                lines.append(line)
        return re.sub(r"\s+", " ", " ".join(lines)).strip()

    def _is_metadata_like(self, text: str) -> bool:
        lowered = str(text or "").strip().lower()
        if not lowered:
            return True
        metadata_markers = [
            "copyright", "all rights reserved", "license", "doi:", "issn", "isbn", "http://", "https://", "www.", "creative commons", "received:", "accepted:", "published:", "journal", "volume", "vol.", "issue", "author", "corresponding author",
        ]
        return any(marker in lowered for marker in metadata_markers) and len(lowered) < 220

    def _trim_to_sentence(self, text: str, limit: int) -> str:
        compact = re.sub(r"\s+", " ", str(text or "")).strip()
        if len(compact) <= limit:
            return compact
        truncated = compact[:limit]
        sentence_endings = [truncated.rfind(mark) for mark in (".", "!", "?")]
        sentence_end = max(sentence_endings)
        if sentence_end > int(limit * 0.55):
            return truncated[: sentence_end + 1].strip()
        return truncated.rsplit(" ", 1)[0].strip()

    def _detect_quiz_language(self, text: str) -> str:
        lowered = text.lower()
        id_markers = ["yang", "dan", "adalah", "dalam", "dengan", "untuk", "pada", "sebagai", "menurut", "dokumen", "penelitian"]
        en_markers = ["the", "and", "is", "are", "with", "for", "from", "according", "document", "research"]
        id_score = sum(1 for marker in id_markers if re.search(rf"\b{re.escape(marker)}\b", lowered))
        en_score = sum(1 for marker in en_markers if re.search(rf"\b{re.escape(marker)}\b", lowered))
        return "id" if id_score >= en_score else "en"

    def _is_generic_question(self, text: str) -> bool:
        lowered = str(text or "").lower()
        generic_patterns = [
            "which statement is supported by",
            "uploaded document",
            "source document",
            "this topic is unrelated",
            "contains only metadata",
            "provides no learning material",
            "file storage setting",
            "browser display option",
        ]
        return any(pattern in lowered for pattern in generic_patterns)

    def _are_options_low_quality(self, options: list[str]) -> bool:
        normalized = [self._normalized_for_scoring(option) for option in options]
        if len(set(normalized)) != len(normalized):
            return True
        if any(self._is_generic_question(option) for option in options):
            return True
        if sum(1 for option in options if len(option) > 220) >= 2:
            return True
        if sum(len(option) for option in options) / max(len(options), 1) > 170:
            return True
        return False

    def _resolve_correct_answer(self, value: object, options: list[str]) -> str:
        answer = self._normalize_answer_value(value)
        if not answer:
            return ""
        normalized_answer = self._normalized_for_scoring(answer)
        for option in options:
            if self._normalized_for_scoring(option) == normalized_answer:
                return option

        key = answer.strip().upper().rstrip(".)")
        if key in {"A", "B", "C", "D"}:
            index = ord(key) - ord("A")
            if 0 <= index < len(options):
                return options[index]
        match = re.match(r"^([A-Da-d])[\).:\s-]+(.+)$", answer.strip())
        if match:
            key_index = ord(match.group(1).upper()) - ord("A")
            if 0 <= key_index < len(options):
                return options[key_index]
        return ""

    def _true_false_options(self, options: object, document_context: dict[str, Any] | None = None) -> list[str]:
        if isinstance(options, list):
            cleaned = [self._normalize_answer_value(option) for option in options if self._normalize_answer_value(option)]
            if len(cleaned) >= 2:
                lowered = {item.lower() for item in cleaned[:2]}
                if lowered & {"true", "benar"} and lowered & {"false", "salah"}:
                    return cleaned[:2]
        language = document_context.get("language") if document_context else "en"
        return ["Benar", "Salah"] if language == "id" else ["True", "False"]

    def _resolve_true_false_answer(self, value: object, options: list[str]) -> str:
        answer = self._normalize_answer_value(value).lower()
        if answer in {"true", "t", "yes", "y", "benar", "betul"}:
            return options[0]
        if answer in {"false", "f", "no", "n", "salah"}:
            return options[1]
        for option in options:
            if self._normalized_for_scoring(option) == self._normalized_for_scoring(answer):
                return option
        return ""

    def _format_chunk_page(self, chunk: DocumentChunk) -> str:
        if not chunk.page_start and not chunk.page_end:
            return "unknown"
        if not chunk.page_end or chunk.page_start == chunk.page_end:
            return str(chunk.page_start or chunk.page_end)
        return f"{chunk.page_start}-{chunk.page_end}"

    def _compact_text(self, text: object, limit: int) -> str:
        compact = re.sub(r"\s+", " ", str(text or "")).strip()
        if len(compact) <= limit:
            return compact
        return compact[:limit].rsplit(" ", 1)[0].strip()

    def _to_quiz_read(self, quiz: Quiz) -> QuizRead:
        metadata = quiz.metadata_ or {}
        questions = sorted(quiz.questions or [], key=lambda item: item.question_order)
        return QuizRead(
            id=quiz.id,
            title=quiz.title,
            source_type=quiz.source_type,
            source_id=quiz.source_document_id,
            topic=quiz.topic,
            difficulty=metadata.get("requested_difficulty") or quiz.difficulty,
            question_type=QuestionType(metadata.get("question_type") or (questions[0].question_type if questions else "multiple_choice")),
            language=str(metadata.get("language") or "id"),
            total_questions=quiz.total_questions,
            generation_message=metadata.get("generation_message"),
            questions=[self._to_question_read(question) for question in questions],
            created_at=quiz.created_at,
            updated_at=quiz.updated_at,
        )

    def _to_question_read(self, question: QuizQuestion) -> QuizQuestionRead:
        return QuizQuestionRead(
            id=question.id,
            question_text=question.question_text,
            question_type=QuestionType(self._normalize_question_type(question.question_type)),
            options=self._options_as_strings(question.options),
            correct_answer=self._correct_answer_value(question),
            explanation=question.explanation,
            topic=question.topic,
            difficulty=(question.metadata_ or {}).get("requested_difficulty") or question.difficulty,
            order_index=question.question_order,
            created_at=question.created_at,
            updated_at=question.updated_at,
        )

    def _to_attempt_read(
        self,
        attempt: QuizAttempt,
        quiz: Quiz | None = None,
        answer_results: list[QuizAnswerResult] | None = None,
    ) -> QuizAttemptRead:
        metadata = attempt.metadata_ or {}
        quiz_obj = quiz or attempt.quiz
        if answer_results is None:
            answer_results = [self._answer_to_result(answer) for answer in sorted(attempt.answers or [], key=lambda item: item.created_at)]
        return QuizAttemptRead(
            id=attempt.id,
            quiz_id=attempt.quiz_id,
            quiz_title=quiz_obj.title if quiz_obj else None,
            score=float(attempt.percentage if attempt.percentage is not None else attempt.score),
            total_questions=int(metadata.get("total_questions") or len(answer_results)),
            correct_count=int(metadata.get("correct_count") or sum(1 for answer in answer_results if answer.is_correct)),
            wrong_count=int(metadata.get("wrong_count") or sum(1 for answer in answer_results if not answer.is_correct)),
            weak_topics=attempt.weak_topics or [],
            recommended_review=metadata.get("recommended_review") or self._recommended_review(attempt.weak_topics or [], str(metadata.get("language") or "id")),
            answers=answer_results,
            started_at=attempt.started_at,
            submitted_at=attempt.submitted_at,
            created_at=attempt.created_at,
            updated_at=attempt.updated_at,
        )

    def _answer_to_result(self, answer: QuizAnswer) -> QuizAnswerResult:
        question = answer.question
        answer_payload = answer.answer or {}
        similarity_score = None
        if isinstance(answer_payload, dict) and answer_payload.get("similarity_score") is not None:
            similarity_score = float(answer_payload["similarity_score"])

        return QuizAnswerResult(
            question_id=answer.question_id,
            question_text=question.question_text if question else "",
            user_answer=self._answer_value(answer.answer),
            correct_answer=self._correct_answer_value(question) if question else "",
            is_correct=bool(answer.is_correct),
            similarity_score=similarity_score,
            feedback=answer.feedback,
            explanation=question.explanation if question else answer.feedback,
            topic=question.topic if question else None,
        )

    def evaluate_short_answer(
        self,
        *,
        user_answer: str,
        correct_answer: str,
        explanation: str | None = None,
        question_text: str | None = None,
        context: str | None = None,
        question_id: uuid.UUID | None = None,
        language: str = "id",
    ) -> dict[str, Any]:
        answer_language = language if language in {"id", "en"} else "id"
        normalized_user = self._normalize_semantic_text(user_answer)
        normalized_correct = self._normalize_semantic_text(correct_answer)

        if not normalized_user or len(normalized_user) < 6:
            result = {
                "is_correct": False,
                "similarity_score": 0,
                "rule_similarity": 0.0,
                "keyword_overlap": 0.0,
                "llm_evaluator_used": False,
                "feedback": self._short_answer_feedback("empty", answer_language),
            }
            self._log_short_answer_scoring(question_id, result)
            return result

        if not normalized_correct:
            result = {
                "is_correct": False,
                "similarity_score": 0,
                "rule_similarity": 0.0,
                "keyword_overlap": 0.0,
                "llm_evaluator_used": False,
                "feedback": self._short_answer_feedback("missing_expected", answer_language),
            }
            self._log_short_answer_scoring(question_id, result)
            return result

        rule_similarity = SequenceMatcher(None, normalized_user, normalized_correct).ratio()
        keyword_source = " ".join([correct_answer or "", explanation or ""])
        important_keywords = self._semantic_keywords(keyword_source)
        if len(important_keywords) < 3:
            important_keywords = self._semantic_keywords(" ".join([correct_answer or "", question_text or "", context or ""]))
        user_keywords = set(self._semantic_keywords(user_answer))
        matched_keywords = [keyword for keyword in important_keywords if keyword in user_keywords or keyword in normalized_user]
        keyword_overlap = len(matched_keywords) / max(len(important_keywords), 1)
        contains_core_keywords = (
            (len(matched_keywords) >= min(3, max(len(important_keywords), 1)) and keyword_overlap >= 0.45)
            or (len(matched_keywords) >= 4 and keyword_overlap >= 0.35)
        )
        rule_score = round(max(rule_similarity, keyword_overlap) * 100)

        if rule_similarity >= 0.65 or keyword_overlap >= 0.55 or contains_core_keywords:
            result = {
                "is_correct": True,
                "similarity_score": max(rule_score, 70),
                "rule_similarity": round(rule_similarity, 3),
                "keyword_overlap": round(keyword_overlap, 3),
                "llm_evaluator_used": False,
                "feedback": self._short_answer_feedback("correct", answer_language),
            }
            self._log_short_answer_scoring(question_id, result)
            return result

        if rule_score < 35 or len(user_keywords) < 2:
            result = {
                "is_correct": False,
                "similarity_score": rule_score,
                "rule_similarity": round(rule_similarity, 3),
                "keyword_overlap": round(keyword_overlap, 3),
                "llm_evaluator_used": False,
                "feedback": self._short_answer_feedback("weak", answer_language),
            }
            self._log_short_answer_scoring(question_id, result)
            return result

        llm_result = self._evaluate_short_answer_with_llm(
            user_answer=user_answer,
            correct_answer=correct_answer,
            explanation=explanation,
            question_text=question_text,
            rule_similarity=rule_similarity,
            keyword_overlap=keyword_overlap,
            language=answer_language,
        )
        if llm_result:
            self._log_short_answer_scoring(question_id, llm_result)
            return llm_result

        result = {
            "is_correct": rule_score >= 55,
            "similarity_score": rule_score,
            "rule_similarity": round(rule_similarity, 3),
            "keyword_overlap": round(keyword_overlap, 3),
            "llm_evaluator_used": False,
            "feedback": self._short_answer_feedback("partial", answer_language) if rule_score < 55 else self._short_answer_feedback("mostly_correct", answer_language),
        }
        self._log_short_answer_scoring(question_id, result)
        return result

    def _evaluate_short_answer_with_llm(
        self,
        *,
        user_answer: str,
        correct_answer: str,
        explanation: str | None,
        question_text: str | None,
        rule_similarity: float,
        keyword_overlap: float,
        language: str,
    ) -> dict[str, Any] | None:
        feedback_language = "Indonesian" if language == "id" else "English"
        system_prompt = (
            "Evaluate whether the student's answer is semantically correct compared to the expected answer. "
            "Do not require exact wording. Accept paraphrases. Mark correct if the core meaning is captured. "
            f"Use {feedback_language} feedback. Return JSON only."
        )
        user_prompt = json.dumps(
            {
                "question": question_text,
                "language": language,
                "expected_answer": correct_answer,
                "student_answer": user_answer,
                "reference_explanation": explanation,
                "rule_similarity": round(rule_similarity, 3),
                "keyword_overlap": round(keyword_overlap, 3),
                "required_schema": {
                    "is_correct": "boolean",
                    "score": "integer 0-100",
                    "feedback": "short feedback string",
                },
            },
            ensure_ascii=False,
        )
        result = llm_service.generate_text_response(system_prompt=system_prompt, user_prompt=user_prompt)
        if result.metadata.get("fallback"):
            return None

        try:
            parsed = json.loads(self._extract_json(result.content))
        except (json.JSONDecodeError, ValueError):
            logger.warning("Short answer LLM evaluator returned invalid JSON.")
            return None

        score = max(0, min(100, int(parsed.get("score") or 0)))
        raw_is_correct = parsed.get("is_correct")
        if isinstance(raw_is_correct, bool):
            is_correct = raw_is_correct
        else:
            is_correct = str(raw_is_correct).strip().lower() in {"true", "yes", "ya", "benar", "correct"}

        return {
            "is_correct": is_correct and score >= 55,
            "similarity_score": score,
            "rule_similarity": round(rule_similarity, 3),
            "keyword_overlap": round(keyword_overlap, 3),
            "llm_evaluator_used": True,
            "feedback": self._compact_text(parsed.get("feedback") or self._short_answer_feedback("llm_default", language), 260),
        }

    def _log_short_answer_scoring(self, question_id: uuid.UUID | None, result: dict[str, Any]) -> None:
        logger.info(
            "Short answer scoring question_id=%s question_type=short_answer rule_similarity=%s keyword_overlap=%s similarity_score=%s llm_evaluator_used=%s is_correct=%s",
            str(question_id) if question_id else None,
            result.get("rule_similarity"),
            result.get("keyword_overlap"),
            result.get("similarity_score"),
            result.get("llm_evaluator_used"),
            result.get("is_correct"),
        )

    def _normalize_semantic_text(self, value: str) -> str:
        lowered = str(value or "").lower()
        lowered = re.sub(r"[^a-z0-9A-ZÀ-ÿ\s]", " ", lowered)
        lowered = re.sub(r"\s+", " ", lowered).strip()
        return lowered

    def _semantic_keywords(self, value: str) -> list[str]:
        stopwords = self._short_answer_stopwords()
        normalized = self._normalize_semantic_text(value)
        tokens = [token for token in normalized.split() if len(token) > 3 and token not in stopwords]
        seen: set[str] = set()
        keywords: list[str] = []
        for token in tokens:
            if token not in seen:
                seen.add(token)
                keywords.append(token)
        return keywords[:18]

    def _short_answer_stopwords(self) -> set[str]:
        return {
            "yang", "dan", "atau", "dari", "adalah", "untuk", "dengan", "pada", "dalam", "sebagai", "karena", "bisa", "dapat", "akan", "tidak", "tanpa", "salah", "satu", "suatu", "yaitu", "merupakan", "secara", "pengguna", "penggunanya",
            "the", "is", "are", "and", "of", "to", "a", "an", "in", "on", "for", "with", "from", "that", "this", "can", "able", "without", "one", "into",
        }

    def _is_correct_by_question_type(self, user_answer: str, correct_answer: str, question_type: str) -> bool:
        if question_type == "true_false":
            return self._normalized_true_false(user_answer) == self._normalized_true_false(correct_answer)
        return self._is_correct(user_answer, correct_answer)

    def _normalized_true_false(self, value: str) -> str:
        normalized = self._normalized_for_scoring(value)
        if normalized in {"true", "t", "yes", "y", "ya", "benar", "betul", "1"}:
            return "true"
        if normalized in {"false", "f", "no", "n", "tidak", "salah", "0"}:
            return "false"
        return normalized
    def _exact_answer_feedback(self, is_correct: bool, language: str) -> str:
        if language == "en":
            return "Correct." if is_correct else "Review the expected answer and explanation."
        return "Benar." if is_correct else "Periksa kembali jawaban yang diharapkan dan penjelasannya."

    def _short_answer_feedback(self, key: str, language: str) -> str:
        messages = {
            "id": {
                "empty": "Jawaban masih terlalu kosong atau terlalu pendek untuk dinilai benar.",
                "missing_expected": "Expected answer belum tersedia, jadi jawaban belum bisa dinilai otomatis.",
                "correct": "Jawaban kamu sudah menangkap inti konsep meskipun tidak sama persis dengan expected answer.",
                "weak": "Jawaban belum cukup memuat ide utama yang diharapkan. Coba sebutkan konsep kunci dengan lebih jelas.",
                "partial": "Jawaban kamu sebagian relevan, tetapi belum cukup kuat untuk dianggap benar penuh.",
                "mostly_correct": "Jawaban kamu cukup menangkap ide utama.",
                "llm_default": "Jawaban dievaluasi secara semantik.",
            },
            "en": {
                "empty": "The answer is too empty or too short to be marked correct.",
                "missing_expected": "The expected answer is not available, so this answer cannot be graded automatically.",
                "correct": "Your answer captures the core meaning even though the wording is different.",
                "weak": "The answer does not include enough of the expected key ideas yet. Try naming the core concept more clearly.",
                "partial": "Your answer is partly relevant, but not strong enough to be marked fully correct.",
                "mostly_correct": "Your answer captures the main idea well enough.",
                "llm_default": "The answer was evaluated semantically.",
            },
        }
        language_key = language if language in messages else "id"
        return messages[language_key].get(key, messages[language_key]["llm_default"])

    def _recommended_review(self, weak_topics: list[str], language: str = "id") -> list[str]:
        if language == "en":
            return [f"Review {topic} with AI Tutor, then retry a short focused quiz." for topic in weak_topics]
        return [f"Pelajari lagi {topic} dengan AI Tutor, lalu coba ulang quiz singkat yang lebih fokus." for topic in weak_topics]

    def _normalize_question_type(self, value: object) -> str:
        normalized = str(value or "multiple_choice").strip().lower()
        return normalized if normalized in {"multiple_choice", "true_false", "short_answer"} else "multiple_choice"

    def _db_difficulty(self, value: object) -> str:
        normalized = str(value or "medium").strip().lower()
        if normalized == "adaptive":
            return "mixed"
        return normalized if normalized in {"easy", "medium", "hard", "mixed"} else "medium"

    def _normalize_options(self, options: object, question_type: str) -> list[str]:
        if question_type == "short_answer":
            return []
        if question_type == "true_false":
            if isinstance(options, list):
                cleaned = [self._normalize_answer_value(option) for option in options if self._normalize_answer_value(option)]
                if len(cleaned) >= 2:
                    lowered = {item.lower() for item in cleaned[:2]}
                    if lowered & {"true", "benar"} and lowered & {"false", "salah"}:
                        return cleaned[:2]
            return ["True", "False"]
        if not isinstance(options, list):
            return []
        return [self._normalize_answer_value(option) for option in options if self._normalize_answer_value(option)]

    def _options_as_strings(self, options: object) -> list[str]:
        if not isinstance(options, list):
            return []
        return [self._normalize_answer_value(option) for option in options]

    def _normalize_answer_value(self, value: object) -> str:
        if isinstance(value, dict):
            value = value.get("value") or value.get("answer") or value.get("text")
        return str(value or "").strip()

    def _answer_value(self, value: object) -> str:
        if isinstance(value, dict):
            return self._normalize_answer_value(value.get("value"))
        return self._normalize_answer_value(value)

    def _correct_answer_value(self, question: QuizQuestion) -> str:
        return self._normalize_answer_value(question.correct_answer)

    def _is_correct(self, user_answer: str, correct_answer: str) -> bool:
        return self._normalized_for_scoring(user_answer) == self._normalized_for_scoring(correct_answer)

    def _normalized_for_scoring(self, value: str) -> str:
        return re.sub(r"\s+", " ", str(value or "").strip().lower())


quiz_service = QuizService()
































