import json
import re
import uuid
from datetime import UTC, date, datetime, timedelta
from typing import Any

from fastapi import HTTPException, status
from sqlalchemy import select
from sqlalchemy.orm import Session, selectinload

from app.models.study_plan import StudyPlan, StudyPlanItem
from app.models.user import User
from app.schemas.study_plan_schema import Priority, StudyPlanGenerateRequest, StudyPlanItemRead, StudyPlanItemUpdateRequest, StudyPlanRead
from app.services.llm_service import llm_service


class StudyPlanService:
    VALID_ITEM_TYPES = {"reading", "practice", "quiz", "revision", "project"}

    def generate_study_plan(
        self,
        db: Session,
        current_user: User,
        payload: StudyPlanGenerateRequest,
    ) -> StudyPlanRead:
        target_days = self._target_days_from_deadline(payload)
        today = date.today()
        system_prompt, user_prompt = self._build_generation_prompt(payload, target_days)
        llm_result = llm_service.generate_text_response(system_prompt=system_prompt, user_prompt=user_prompt)
        generation_message = None

        try:
            plan_data = self._parse_llm_plan(llm_result.content)
            generation_message = "Study plan generated by LLM."
        except ValueError as exc:
            plan_data = self._fallback_plan(payload, target_days)
            generation_message = f"Development fallback used: {exc}"

        if llm_result.metadata.get("fallback"):
            plan_data = self._fallback_plan(payload, target_days)
            generation_message = f"Development fallback used: {llm_result.content}"

        original_llm_item_count = len(plan_data.get("items") or [])
        plan_data["items"] = self.normalize_study_plan_items(
            items=plan_data.get("items") or [],
            target_days=target_days,
            payload=payload,
        )
        normalized_item_count = len(plan_data["items"])

        self._archive_existing_active_plans(db, current_user.id)

        plan = StudyPlan(
            user_id=current_user.id,
            title=plan_data["title"],
            description=plan_data.get("description"),
            goal=payload.learning_goal,
            level=payload.understanding_level,
            weekly_hours=self._weekly_hours(payload.study_duration_per_day),
            start_date=today,
            end_date=payload.deadline_date,
            status="active",
            generated_by_ai=True,
            model_name=llm_result.model,
            metadata_={
                "subject": payload.subject,
                "topic": payload.topic,
                "deadline_date": payload.deadline_date.isoformat() if payload.deadline_date else None,
                "study_duration_per_day": payload.study_duration_per_day,
                "understanding_level": payload.understanding_level,
                "preferred_learning_style": payload.preferred_learning_style,
                "weak_topics": payload.weak_topics,
                "llm_provider": llm_result.provider,
                "llm_model": llm_result.model,
                "generation_message": generation_message,
                "adaptive_suggestion": plan_data.get("adaptive_suggestion"),
                "target_days": target_days,
                "generated_from_deadline": payload.deadline_date is not None,
                "original_llm_item_count": original_llm_item_count,
                "normalized_item_count": normalized_item_count,
            },
        )
        db.add(plan)
        db.flush()

        for index, item_data in enumerate(plan_data["items"], start=1):
            db.add(
                StudyPlanItem(
                    study_plan_id=plan.id,
                    user_id=current_user.id,
                    title=item_data["title"],
                    description=item_data.get("description"),
                    item_type=self._normalize_item_type(item_data.get("item_type")),
                    topic=payload.topic,
                    due_date=today + timedelta(days=index - 1),
                    estimated_minutes=int(item_data.get("estimated_minutes") or payload.study_duration_per_day),
                    sort_order=index,
                    status="todo",
                    metadata_={
                        "day_number": index,
                        "priority": self._normalize_priority(item_data.get("priority")),
                        "recommended_resource": item_data.get("recommended_resource"),
                    },
                )
            )

        db.commit()
        db.refresh(plan)
        return self.get_study_plan(db=db, current_user=current_user, plan_id=plan.id)

    def get_study_plans(self, db: Session, current_user: User) -> list[StudyPlanRead]:
        plans = db.scalars(
            select(StudyPlan)
            .options(selectinload(StudyPlan.items))
            .where(StudyPlan.user_id == current_user.id)
            .order_by(StudyPlan.created_at.desc())
        ).all()
        return [self._to_plan_read(plan) for plan in plans]

    def get_active_study_plan(self, db: Session, current_user: User) -> StudyPlanRead:
        plan = db.scalar(
            select(StudyPlan)
            .options(selectinload(StudyPlan.items))
            .where(StudyPlan.user_id == current_user.id, StudyPlan.status == "active")
            .order_by(StudyPlan.created_at.desc())
        )
        if not plan:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Active study plan not found.")
        return self._to_plan_read(plan)

    def get_study_plan(self, db: Session, current_user: User, plan_id: uuid.UUID) -> StudyPlanRead:
        plan = db.scalar(
            select(StudyPlan)
            .options(selectinload(StudyPlan.items))
            .where(StudyPlan.id == plan_id, StudyPlan.user_id == current_user.id)
        )
        if not plan:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Study plan not found.")
        return self._to_plan_read(plan)

    def complete_item(self, db: Session, current_user: User, item_id: uuid.UUID) -> StudyPlanRead:
        item = self._get_user_item(db, current_user, item_id)
        item.status = "done"
        item.completed_at = datetime.now(UTC)
        plan = item.study_plan
        self._sync_plan_status(plan)
        db.commit()
        db.refresh(plan)
        return self.get_study_plan(db=db, current_user=current_user, plan_id=plan.id)

    def uncomplete_item(self, db: Session, current_user: User, item_id: uuid.UUID) -> StudyPlanRead:
        item = self._get_user_item(db, current_user, item_id)
        item.status = "todo"
        item.completed_at = None
        plan = item.study_plan
        if plan.status == "completed":
            plan.status = "active"
        db.commit()
        db.refresh(plan)
        return self.get_study_plan(db=db, current_user=current_user, plan_id=plan.id)

    def update_study_plan_item(
        self,
        db: Session,
        current_user: User,
        item_id: uuid.UUID,
        payload: StudyPlanItemUpdateRequest,
    ) -> StudyPlanRead:
        item = self._get_user_item(db, current_user, item_id)
        changes = payload.model_dump(exclude_unset=True, mode="json")

        if "title" in changes and changes["title"] is not None:
            item.title = changes["title"]
        if "description" in changes:
            item.description = changes["description"]
        if "estimated_minutes" in changes and changes["estimated_minutes"] is not None:
            item.estimated_minutes = changes["estimated_minutes"]

        metadata = dict(item.metadata_ or {})
        if "priority" in changes and changes["priority"] is not None:
            metadata["priority"] = self._normalize_priority(changes["priority"])
        if "recommended_resource" in changes:
            metadata["recommended_resource"] = changes["recommended_resource"]
        item.metadata_ = metadata

        plan = item.study_plan
        self._sync_plan_status(plan, activate_when_incomplete=True)
        db.commit()
        db.refresh(plan)
        return self.get_study_plan(db=db, current_user=current_user, plan_id=plan.id)

    def delete_study_plan_item(self, db: Session, current_user: User, item_id: uuid.UUID) -> StudyPlanRead:
        item = self._get_user_item(db, current_user, item_id)
        plan = item.study_plan
        plan_id = plan.id

        db.delete(item)
        db.flush()
        remaining_items = self._renumber_plan_items(db=db, plan_id=plan_id, user_id=current_user.id)
        self._sync_plan_status(plan, items=remaining_items, activate_when_incomplete=True)
        db.commit()
        return self.get_study_plan(db=db, current_user=current_user, plan_id=plan_id)

    def delete_study_plan(self, db: Session, current_user: User, plan_id: uuid.UUID) -> None:
        plan = db.scalar(select(StudyPlan).where(StudyPlan.id == plan_id, StudyPlan.user_id == current_user.id))
        if not plan:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Study plan not found.")
        db.delete(plan)
        db.commit()

    def _get_user_item(self, db: Session, current_user: User, item_id: uuid.UUID) -> StudyPlanItem:
        item = db.scalar(
            select(StudyPlanItem)
            .join(StudyPlan, StudyPlanItem.study_plan_id == StudyPlan.id)
            .options(selectinload(StudyPlanItem.study_plan))
            .where(StudyPlanItem.id == item_id, StudyPlanItem.user_id == current_user.id, StudyPlan.user_id == current_user.id)
        )
        if not item:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Study plan item not found.")
        return item

    def _archive_existing_active_plans(self, db: Session, user_id: uuid.UUID) -> None:
        active_plans = db.scalars(select(StudyPlan).where(StudyPlan.user_id == user_id, StudyPlan.status == "active")).all()
        for plan in active_plans:
            plan.status = "archived"

    def _sync_plan_status(
        self,
        plan: StudyPlan,
        items: list[StudyPlanItem] | None = None,
        activate_when_incomplete: bool = False,
    ) -> None:
        plan_items = list(items if items is not None else plan.items or [])
        if plan_items and all(item.status == "done" for item in plan_items):
            plan.status = "completed"
            return
        if activate_when_incomplete or plan.status == "completed":
            plan.status = "active"

    def _renumber_plan_items(self, db: Session, plan_id: uuid.UUID, user_id: uuid.UUID) -> list[StudyPlanItem]:
        items = db.scalars(
            select(StudyPlanItem)
            .where(StudyPlanItem.study_plan_id == plan_id, StudyPlanItem.user_id == user_id)
            .order_by(StudyPlanItem.sort_order.asc(), StudyPlanItem.created_at.asc())
        ).all()
        for index, item in enumerate(items, start=1):
            item.sort_order = index
            metadata = dict(item.metadata_ or {})
            metadata["day_number"] = index
            item.metadata_ = metadata
        return list(items)

    def _to_plan_read(self, plan: StudyPlan) -> StudyPlanRead:
        metadata = plan.metadata_ or {}
        items = sorted(plan.items or [], key=lambda item: item.sort_order)
        return StudyPlanRead(
            id=plan.id,
            title=plan.title,
            description=plan.description,
            learning_goal=plan.goal,
            subject=metadata.get("subject"),
            topic=metadata.get("topic"),
            deadline_date=plan.end_date or self._parse_date(metadata.get("deadline_date")),
            study_duration_per_day=metadata.get("study_duration_per_day"),
            understanding_level=plan.level or metadata.get("understanding_level"),
            preferred_learning_style=metadata.get("preferred_learning_style"),
            weak_topics=metadata.get("weak_topics") or [],
            status=plan.status,
            progress_percentage=self._progress_percentage(items),
            generation_message=metadata.get("generation_message"),
            items=[self._to_item_read(item) for item in items],
            created_at=plan.created_at,
            updated_at=plan.updated_at,
        )

    def _to_item_read(self, item: StudyPlanItem) -> StudyPlanItemRead:
        metadata = item.metadata_ or {}
        return StudyPlanItemRead(
            id=item.id,
            day_number=int(metadata.get("day_number") or item.sort_order or 1),
            title=item.title,
            description=item.description,
            estimated_minutes=item.estimated_minutes,
            priority=Priority(self._normalize_priority(metadata.get("priority"))),
            recommended_resource=metadata.get("recommended_resource"),
            is_completed=item.status == "done",
            completed_at=item.completed_at,
            created_at=item.created_at,
            updated_at=item.updated_at,
        )

    def _progress_percentage(self, items: list[StudyPlanItem]) -> int:
        if not items:
            return 0
        completed_count = sum(1 for item in items if item.status == "done")
        return round((completed_count / len(items)) * 100)

    def _weekly_hours(self, study_duration_per_day: int) -> int:
        return max(1, round((study_duration_per_day * 7) / 60))

    def _target_days_from_deadline(self, payload: StudyPlanGenerateRequest) -> int:
        if not payload.deadline_date:
            return 7

        today = date.today()
        if payload.deadline_date < today:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="Deadline date must be today or in the future.",
            )
        return max(1, (payload.deadline_date - today).days + 1)

    def _normalize_item_type(self, value: object) -> str:
        normalized = str(value or "practice").strip().lower()
        return normalized if normalized in self.VALID_ITEM_TYPES else "practice"

    def _coerce_minutes(self, value: object, fallback: int) -> int:
        try:
            minutes = int(value or fallback)
        except (TypeError, ValueError):
            minutes = fallback
        return max(10, min(480, minutes))

    def _coerce_day_number(self, value: object, fallback: int) -> int:
        try:
            day_number = int(value or fallback)
        except (TypeError, ValueError):
            day_number = fallback
        return max(1, day_number)

    def _normalize_priority(self, value: object) -> str:
        normalized = str(value or "medium").strip().lower()
        return normalized if normalized in {"low", "medium", "high"} else "medium"

    def _parse_date(self, value: object) -> date | None:
        if not value:
            return None
        try:
            return date.fromisoformat(str(value))
        except ValueError:
            return None

    def _build_generation_prompt(self, payload: StudyPlanGenerateRequest, target_days: int) -> tuple[str, str]:
        system_prompt = (
            "You are EduPath AI Study Plan Generator. Return only valid JSON. "
            "Do not wrap the JSON in markdown. Do not include commentary outside the JSON. "
            f"Generate exactly {target_days} daily study tasks."
        )
        user_prompt = json.dumps(
            {
                "instruction": "Create a personalized study plan as valid JSON.",
                "target_days": target_days,
                "required_schema": {
                    "title": "string",
                    "description": "string",
                    "adaptive_suggestion": "string",
                    "items": [
                        {
                            "day_number": "integer",
                            "title": "string",
                            "description": "string",
                            "estimated_minutes": "integer",
                            "priority": "low|medium|high",
                            "recommended_resource": "string",
                            "item_type": "reading|practice|quiz|revision|project",
                        }
                    ],
                },
                "rules": [
                    f"Generate exactly {target_days} daily study tasks.",
                    f"Use day_number from 1 to {target_days}, with no missing days and no duplicate day_number values.",
                    "Create one main task per day.",
                    "Do not stop early.",
                    "Respect the user deadline and distribute learning across the full date range.",
                    "Each task estimated_minutes should align with study_duration_per_day.",
                    "Prioritize weak topics early, then review, practice, quiz, and final self-assessment.",
                    "Use practical tasks that can be completed by a student.",
                    "Output valid JSON only.",
                ],
                "input": payload.model_dump(mode="json"),
            },
            ensure_ascii=False,
        )
        return system_prompt, user_prompt

    def _parse_llm_plan(self, content: str) -> dict[str, Any]:
        json_text = self._extract_json(content)
        try:
            parsed = json.loads(json_text)
        except json.JSONDecodeError as exc:
            raise ValueError("LLM did not return valid JSON.") from exc

        items = parsed.get("items")
        if not isinstance(parsed.get("title"), str) or not parsed.get("title").strip():
            raise ValueError("LLM JSON is missing title.")
        if not isinstance(items, list) or not items:
            raise ValueError("LLM JSON is missing items.")

        normalized_items = []
        for index, item in enumerate(items, start=1):
            if not isinstance(item, dict) or not str(item.get("title") or "").strip():
                continue
            normalized_items.append(
                {
                    "day_number": self._coerce_day_number(item.get("day_number"), index),
                    "title": str(item["title"]).strip(),
                    "description": str(item.get("description") or "").strip(),
                    "estimated_minutes": self._coerce_minutes(item.get("estimated_minutes"), 30),
                    "priority": self._normalize_priority(item.get("priority")),
                    "recommended_resource": str(item.get("recommended_resource") or "AI Tutor").strip(),
                    "item_type": self._normalize_item_type(item.get("item_type")),
                }
            )

        if not normalized_items:
            raise ValueError("LLM JSON items are empty after validation.")

        return {
            "title": parsed["title"].strip(),
            "description": str(parsed.get("description") or "").strip(),
            "adaptive_suggestion": str(parsed.get("adaptive_suggestion") or "").strip(),
            "items": normalized_items,
        }

    def normalize_study_plan_items(
        self,
        items: list[dict[str, Any]],
        target_days: int,
        payload: StudyPlanGenerateRequest,
    ) -> list[dict[str, Any]]:
        sorted_items = sorted(
            [item for item in items if isinstance(item, dict)],
            key=lambda item: self._coerce_day_number(item.get("day_number"), len(items) + 1),
        )
        fallback_minutes = payload.study_duration_per_day
        normalized_items: list[dict[str, Any]] = []

        for day_number in range(1, target_days + 1):
            source = sorted_items[day_number - 1] if day_number - 1 < len(sorted_items) else None
            fallback_item = self._build_fallback_item(day_number, target_days, payload)

            if not source:
                normalized_items.append(fallback_item)
                continue

            title = str(source.get("title") or "").strip() or fallback_item["title"]
            description = str(source.get("description") or "").strip() or fallback_item["description"]
            normalized_items.append(
                {
                    "day_number": day_number,
                    "title": title,
                    "description": description,
                    "estimated_minutes": self._coerce_minutes(source.get("estimated_minutes"), fallback_minutes),
                    "priority": self._normalize_priority(source.get("priority") or fallback_item["priority"]),
                    "recommended_resource": str(source.get("recommended_resource") or fallback_item["recommended_resource"]).strip(),
                    "item_type": self._normalize_item_type(source.get("item_type") or fallback_item["item_type"]),
                }
            )

        return normalized_items

    def _build_fallback_item(self, day_number: int, target_days: int, payload: StudyPlanGenerateRequest) -> dict[str, Any]:
        weak_topics = payload.weak_topics or [payload.topic]
        focus_topic = weak_topics[(day_number - 1) % len(weak_topics)] if weak_topics else payload.topic
        topic = payload.topic or payload.subject
        minutes = payload.study_duration_per_day

        if day_number == 1:
            return {
                "day_number": day_number,
                "title": f"Map the essentials of {topic}",
                "description": f"Review the learning goal, identify what you already know, and ask AI Tutor for a simple overview of {topic}.",
                "estimated_minutes": minutes,
                "priority": "high",
                "recommended_resource": "AI Tutor",
                "item_type": "revision",
            }

        if day_number == target_days:
            return {
                "day_number": day_number,
                "title": f"Final self-assessment for {topic}",
                "description": "Take a mixed quiz, review mistakes, and save the most important takeaways before the deadline.",
                "estimated_minutes": minutes,
                "priority": "high",
                "recommended_resource": "Quiz Arena",
                "item_type": "quiz",
            }

        pattern = (day_number - 2) % 4
        if pattern == 0:
            return {
                "day_number": day_number,
                "title": f"Strengthen {focus_topic}",
                "description": f"Study {focus_topic} with a focused explanation, then write a short summary in your own words.",
                "estimated_minutes": minutes,
                "priority": "high" if focus_topic in (payload.weak_topics or []) else "medium",
                "recommended_resource": "AI Tutor",
                "item_type": "reading",
            }
        if pattern == 1:
            return {
                "day_number": day_number,
                "title": f"Practice examples for {topic}",
                "description": "Work through guided examples and compare your reasoning with the solution explanation.",
                "estimated_minutes": minutes,
                "priority": "medium",
                "recommended_resource": "AI Tutor",
                "item_type": "practice",
            }
        if pattern == 2:
            return {
                "day_number": day_number,
                "title": f"Focused quiz on {focus_topic}",
                "description": "Generate a short quiz, review every incorrect answer, and note the pattern behind each mistake.",
                "estimated_minutes": minutes,
                "priority": "high",
                "recommended_resource": "Quiz Arena",
                "item_type": "quiz",
            }
        return {
            "day_number": day_number,
            "title": f"Review and connect {topic}",
            "description": f"Connect today's concepts to the main goal: {payload.learning_goal}. Save concise notes for later review.",
            "estimated_minutes": minutes,
            "priority": "medium",
            "recommended_resource": "Saved Notes",
            "item_type": "revision",
        }

    def _extract_json(self, content: str) -> str:
        cleaned = content.strip()
        fence_match = re.search(r"```(?:json)?\s*(.*?)```", cleaned, re.DOTALL | re.IGNORECASE)
        if fence_match:
            cleaned = fence_match.group(1).strip()

        start = cleaned.find("{")
        end = cleaned.rfind("}")
        if start == -1 or end == -1 or end <= start:
            raise ValueError("LLM response does not contain a JSON object.")
        return cleaned[start : end + 1]

    def _fallback_plan(self, payload: StudyPlanGenerateRequest, target_days: int | None = None) -> dict[str, Any]:
        days = target_days or self._target_days_from_deadline(payload)
        weak_topics = payload.weak_topics or [payload.topic]
        first_weak_topic = weak_topics[0] if weak_topics else payload.topic
        return {
            "title": f"{payload.topic} Learning Sprint",
            "description": f"A personalized plan for {payload.subject} focused on {payload.learning_goal}.",
            "adaptive_suggestion": f"Start with {first_weak_topic}. If confidence is low, repeat review before quiz practice.",
            "items": [self._build_fallback_item(day_number, days, payload) for day_number in range(1, days + 1)],
        }

study_plan_service = StudyPlanService()


